### PR TITLE
Eat erroneous tokens at the beginning of command

### PR DESCRIPTION
**Pull request by jvanloov**
Kaldi often recognizes 'I' or 'the' as the first token of a command. This implements a rule that swallows these tokens, so that the command is still recognized correctly.

(issue #25 describes this issue too)

### CODE REVIEW

**Comment by dwks** [comment]
I don't think this will work as written because the code sometimes says `junk_token` and sometimes `junk_tokens`. I like the general idea, and I would also add "a" to the word list. However, this behaviour is specific to the current kaldi model, and we might want to revert it eventually. What do you think about having two root rules `single_input` and `single_input_discard_junk` which we can switch between programmatically? EDIT: probably not worth the complexity now that I think about it.

**Comment by jvanloov** [comment]
I have implemented your suggestion anyway, because I want to keep using the 'swallowing' behavior myself, and the suggestion to be able to switch it off easily makes sense. I modified the commit in the pull request, feel free to review it again and include it if you wish.

**Comment by dwks** [comment]
This looks clean. Thank you!

**Comment by dwks** [comment]
There was a small bug which I have fixed and pushed, cheers. I also implemented "to"/"for" for "two"/"four" at the same time.

**Pull request merged**
